/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 DigiCard2.glb --transform -types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['shiny metal']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/DigiCard2-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane003.geometry} material={materials.Material} />
      <mesh castShadow receiveShadow geometry={nodes.Plane003_1.geometry} material={materials['shiny metal']} />
    </group>
  )
}

useGLTF.preload('/DigiCard2-transformed.glb')
