import { Project } from "./types";

export const projects: Project[] = [
  {
    id: "1",
    year: "2002",
    title: "Project One long description",
    type: "commercial",
    description: "this is the project description",
    images: [
      { imageId: "1", imagePath: "/images/toothpaste.jpeg" },
      { imageId: "2", imagePath: "/images/sink.jpeg" },
    ],
  },
  {
    id: "2",
    year: "2003",
    title: "Project Two",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/sink.jpeg" }],
  },
  {
    id: "3",
    year: "2004",
    title: "Project Three",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "3", imagePath: "/images/cat.png" }],
  },
  {
    id: "4",
    year: "2003",
    title: "Project Four",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/sink.jpeg" }],
  },
  {
    id: "5",
    year: "2003",
    title: "Project Five",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/sink.jpeg" }],
  },
  {
    id: "6",
    year: "2003",
    title: "Project Six",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/sink.jpeg" }],
  },
  {
    id: "7",
    year: "2003",
    title: "Project Seven",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/sink.jpeg" }],
  },
  {
    id: "8",
    year: "2003",
    title: "Project Eight",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/sink.jpeg" }],
  },
  {
    id: "9",
    year: "2003",
    title: "Project Nine",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/toothpaste.jpeg" }],
  },
  {
    id: "10",
    year: "2003",
    title: "Project Ten",
    type: "personal",
    description: "this is the project description",
    images: [{ imageId: "2", imagePath: "/images/sink.jpeg" }],
  },
];
